id: I927B82D2
legacy_id: null
ocr_import_info:
  bdrc_scan_id: W1KG10787
  source: bdrc.io
  batch_id: batch003
  software_id: vision
  expected_default_language: bo
  ocr_info: {}
  op_import_options: {}
  op_import_version: 0.9.7
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-11-01T09:17:15.244739+00:00'
last_modified: '2022-11-01T09:17:15.244745+00:00'
parser: null
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG10787
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG10787
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ།  བྲག་གཡབ་བློ་བཟང་ནོར་བུ། ༼བྲག་གཡབ་བུ་དགོན་གྱི་པར་མ།༽
  languages:
  - bo
  author: བློ་བཟང་ནོར་བུ།
statistics:
  ocr_word_mean_confidence_index: 0.8882577371303665
  ocr_word_median_confidence_index: 0.958077085
quality: null
bases:
  I1KG10828:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10828
      total_pages: 888
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG10828.txt
    statistics:
      ocr_word_median_confidence_index: 0.958077085
      ocr_word_mean_confidence_index: 0.8882577371303665
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
